# -*- coding: utf-8 -*-
"""hp2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CKyv-xZKHLf3IPm-sriKrGYAtMhHH15B
"""



#동전의 개수가 최소가 되도록 큰 단위의 동전이 우선순위를 가짐
def exchange(price):
  n500=price//500
  price%=500
  n100=price//100
  price%=100
  n50=price//50
  price%=50
  n10=price//10

  print('500원 동전의 개수: ',n500)
  print('100원 동전의 개수: ',n100)
  print('50원 동전의 개수: ',n50)
  print('10원 동전의 개수: ',n10)

def get_integer(prompt):
  res=int(input(prompt))
  return res


A=get_integer('동전으로 교환하고자 하는 금액은?')
B=exchange(A)