# -*- coding: utf-8 -*-
"""hw3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1na2Iu6iB41IwSoWns16tbIhUY-E8cJ2x
"""

#숙제,상품의 할인율과 할인가격을 전달받아 상품의 할인 전 가격을 계산하는 코드 작성.
#201911103 이영기

def get_fixed_price(rate,price):

  realprice=price/(1-rate/100)
  return realprice

rate=int(input('할인율은?'))

A=int(input('A 상품의 할인된 가격은?'))
B=int(input('B 상품의 할인된 가격은?'))
print('A 상품의 정가는',get_fixed_price(rate,A),'원')
print('B 상품의 정가는',get_fixed_price(rate,B),'원')