# -*- coding: utf-8 -*-
"""hw4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G3XaQdOL2EG-OrctBM4NSO6aLjentygg
"""

#개념 확인 과제
#201911103 이영기
def rep_char(c,n):
  print(c*n)

def draw_line_string(name):
  msg1= 'Hello ' + name
  msg2= 'Welcome to Seoul.'
  nstr=len(msg1) if (len(msg1)>len(msg2)) else len(msg2)
  rep_char('-',nstr+2)
  print(f' {msg1}, ', f'\n {msg2} ')
  rep_char('-',nstr+2)

name=input('input his/her name:')
draw_line_string(name)