# -*- coding: utf-8 -*-
"""hw5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YzL8jou5hXy9_whz99js-7D_IVjrdkEu
"""

# 사용자로부터 세자리 이하의 10진 정수 입력받아서 각 자릿수를 한글로 읽어주는 프로그램 작성
#함수 read_single_digit() 은 임의의 한자리 10진 정수에 대한 한글 문자열로 반환
#함수 read_number() 은 임의의 세자리 10진 정수에 대한 한글 문자열로 반환
#201911103 이영기

def read_single_digit(a):
  if a== 1:
    return '일'
  if a== 2:
    return '이'
  if a== 3:
    return '삼'
  if a== 4:
    return '사'
  if a== 5:
    return '오'
  if a== 6:
    return '육'
  if a== 7:
    return '칠'
  if a== 8:
    return '팔'
  if a== 9:
    return '구'
  if a== 0:
    return '영'

def read_number(b):
  n1=b//100
  n2=(b%100)//10
  n3=(b%100)%10
  n1=read_single_digit(n1)
  n2=read_single_digit(n2)
  n3=read_single_digit(n3)
  return print(n1, n2, n3)

c=read_number(int(input('세 자리 정수 입력: ')))