# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDrr1cLqacXi0rbVikQweCf9bBdV4o-J
"""

#숙제
#구구단 출력
#입력받은 정수에 대해 구구단 한 단을 출력
#단 0 또는 음수입력시 다시 입력
#n= 사용자료부터 양의정수 입력받음
# n단에 대한 구구단표 출력


# for i를 1부터 9까지 반복
#단 두자리면 밀려서 출력되지 않도록 하기
def display_multiplication_table(n):


    for i in range(1,10):

      for j in range(n,n+4):
        print(f'{j} x {i} = {j*i:2d}',end='\t') # :2d가 무슨 뜻이면 f 문자열에서 빈자리 두칸을 확보 했단 의미 그리고 오른쪽 정렬을 했음
      print()
    print()


display_multiplication_table(2)
display_multiplication_table(6)