# -*- coding: utf-8 -*-
"""hw7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fwoGsVRRaJj80pPAocBV5lCybytYGj0
"""

#과제 201911103 이영기
shopping_bag={}
print('[구입]')
while True:
  item=input('상품명? ')
  if item == '':
    break
  else:
    much=int(input('수량은? '))
    shopping_bag[item]=much
    print(f'장바구니에 {item}가 {much}개가 담겼습니다.\n')
print(f'\n>>>장바구니 보기: {shopping_bag}\n\n[검색]\n')
a=input('장바구니에서  확인하고자 하는 상품은? ')
b=shopping_bag[a]
print(f'{a}은(는) {b}개 담겨 있습니다.')