# -*- coding: utf-8 -*-
"""hw9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7m_pB83U1V-5S5OUEMsqfuMyWOkjCW1
"""

# 개념확인과제 (연습문제11.3) 201911103 이영기
#2차원 화면의 직사각형 둘레와 넓이 구하기

class Point:
  def __init__(self,x,y):
    self.x=x
    self.y=y

class Rectangle():
  def __init__(self,x1,y1,x2,y2):
   self.lt = Point(x1,y1)
   self.rb = Point(x2,y2)

  def show(self):
    print(f'좌측 상단 꼭지점이({self.lt.x}, {self.lt.y})이고 우측 하단 꼭지점이 ({self.rb.x}, {self.rb.y})인 사각형입니다.')

  def getWidth(self):
    w=self.rb.x-self.lt.x
    return w

  def getHeight(self):
    h=self.rb.y-self.lt.y
    return h

  def getArea(self):
    w=self.getWidth()
    h=self.getHeight()
    a= w*h
    return a


  def getPerimeter(self):
    w=self.getWidth()
    h=self.getHeight()
    return 2*(w+h)



# 주 프로그램부

r1 = Rectangle(5,5,20,10)
a=r1.getArea()
p=r1.getPerimeter()

r1.show()
print(f'\n넓이는 {a}, 둘레는 {p}')